kind: ClusterRoleBinding  
apiVersion: rbac.authorization.k8s.io/v1  
metadata:  
  name: deploy-pod-editor
subjects:  
- kind: User
  name: deploy_edit
  apiGroup: rbac.authorization.k8s.io
roleRef:  
  kind: ClusterRole
  name: deploy-pod-editor
  apiGroup: rbac.authorization.k8s.io
