kind: ClusterRoleBinding  
apiVersion: rbac.authorization.k8s.io/v1  
metadata:  
  name: deploy-pod-viewer
subjects:  
- kind: User
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io
roleRef:  
  kind: ClusterRole
  name: deploy-pod-viewer
  apiGroup: rbac.authorization.k8s.io
