kind: RoleBinding  
apiVersion: rbac.authorization.k8s.io/v1  
metadata:  
  name: prod-admin-user-binding
  namespace: prod
subjects:  
- kind: User
  name: prod_admin
  apiGroup: rbac.authorization.k8s.io
roleRef:  
  kind: ClusterRole
  name: admin-ns-prod
  apiGroup: rbac.authorization.k8s.io
