kind: RoleBinding  
apiVersion: rbac.authorization.k8s.io/v1  
metadata:  
  name: prod-view-user-binding
  namespace: prod
subjects:  
- kind: User
  name: prod_view
  apiGroup: rbac.authorization.k8s.io
roleRef:  
  kind: ClusterRole
  name: view-ns-prod
  apiGroup: rbac.authorization.k8s.io
