---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-namespace-admin
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-namespace-admin-full-access
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-namespace-admin-full-access
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-namespace-admin
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-namespace-admin-full-access
